[build-system]
requires = [
    "setuptools",
    "wget"
]

[tool.poetry]
name        = "pydp"
version     = "1.1.5.rc4"
description = ""
authors     = [
    "Chinmay Shah <chinmayshah3899@gmail.com>",
]
license     = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
black            = "*"
isort            = "*"
mypy             = "*"
nbqa             = "*"
numpy            = "*"
pre-commit       = "*"
pytest           = "*"
pytest-randomly  = "*"
pytest-sugar     = "*"
pytest-xdist     = "*"
setuptools       = "*"
sphinx           = "*"
sphinx-rtd-theme = "*"
twine            = "*"
wheel            = "*"
