name: Tests

on:
  schedule:
    - cron: "30 20 * * *" # 7:30pm UTC
  workflow_dispatch:
  pull_request:
    paths:
      - "*.cpp"
      - "*.c"
      - "*.cc"
      - "*.hpp"
      - "*.h"
      - "*.py"
      - "*.ipynb"
      - "*.go"
      - "*.mod"
      - "*.toml"
      - "*.txt"
      - "setup.cfg"
      - ".github/workflows/*.yml"
      - "CMakeLists.txt"

jobs:
  linting:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install python dependencies
        run: |
          pip install black mypy
      - name: Black
        run: |
          black .
      - name: MyPY
        run: |
          mypy src tests
      - name: Run clang-format style check for C/C++ programs.
        uses: jidicula/clang-format-action@v4.11.0
        with:
          clang-format-version: "11"
          check-path: "/src/bindings/"
          fallback-style: "Google"

  build:
    runs-on: ${{ matrix.os }}
    needs: [linting]
    strategy:
      fail-fast: false
      max-parallel: 12
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.11", "3.12", "3.13", "3.14"]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build Google DP
        timeout-minutes: 20
        run: |
          bash build_PyDP.sh

      - name: Upgrade pip
        run: |
          pip install --upgrade --user pip

      - name: Install Poetry
        run: |
          pip install poetry

      - name: Get poetry cache dir
        id: poetry-cache
        run: |
          echo "dir=$(poetry config cache-dir)" >> $GITHUB_OUTPUT

      - name: poetry cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.poetry-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-py${{ matrix.python-version }}-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-py${{ matrix.python-version }}-

      - name: Install dependencies
        run: |
          poetry install

      - name: Build PyDP macOS
        if: runner.os == 'macOS'
        run: |
          poetry run python setup.py build bdist_wheel

      - name: Build PyDP Linux
        if: runner.os == 'Linux'
        run: |
          poetry run python setup.py build bdist_wheel

      - name: Install Wheel Unix
        run: |
          pip install `find -L ./ -name "*.whl"`

      - name: Import Package
        run: |
          python -c "import pydp; print(pydp.__version__)"

      - name: Run Pytest
        run: |
          poetry run pytest tests -n auto
